application: dsm2grid
version: utils
runtime: python
api_version: 1

handlers:
- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: .*
  script: main.py
  login: admin

builtins:
- datastore_admin: on
